// Code generated by "stringer -type=ScriptType -output generated.scripttype_string.go"; DO NOT EDIT.

package functions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownScriptType-0]
	_ = x[MapScriptType-1]
	_ = x[FilterScriptType-2]
	_ = x[FoldScriptType-3]
	_ = x[SortScriptType-4]
	_ = x[FlatScriptType-5]
	_ = x[LiftScriptType-6]
}

const _ScriptType_name = "UnknownScriptTypeMapScriptTypeFilterScriptTypeFoldScriptTypeSortScriptTypeFlatScriptTypeLiftScriptType"

var _ScriptType_index = [...]uint8{0, 17, 30, 46, 60, 74, 88, 102}

func (i ScriptType) String() string {
	if i < 0 || i >= ScriptType(len(_ScriptType_index)-1) {
		return "ScriptType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScriptType_name[_ScriptType_index[i]:_ScriptType_index[i+1]]
}
