// Code generated by "stringer -type=Code -output generated.code_string.go"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Normal-1]
	_ = x[System-2]
	_ = x[Parse-3]
	_ = x[Translate-4]
	_ = x[IO-5]
	_ = x[Validate-6]
	_ = x[Iterator-7]
	_ = x[Conversion-8]
	_ = x[Fold-9]
	_ = x[Map-10]
	_ = x[Filter-11]
	_ = x[Consume-12]
	_ = x[Sort-13]
	_ = x[Lift-14]
	_ = x[Flat-15]
}

const _Code_name = "UnknownNormalSystemParseTranslateIOValidateIteratorConversionFoldMapFilterConsumeSortLiftFlat"

var _Code_index = [...]uint8{0, 7, 13, 19, 24, 33, 35, 43, 51, 61, 65, 68, 74, 81, 85, 89, 93}

func (i Code) String() string {
	if i < 0 || i >= Code(len(_Code_index)-1) {
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Code_name[_Code_index[i]:_Code_index[i+1]]
}
