// Code generated by "stringer -type=Type -output generated.type_string.go"; DO NOT EDIT.

package flat

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeSimple-1]
	_ = x[TypePerfect-2]
}

const _Type_name = "TypeUnknownTypeSimpleTypePerfect"

var _Type_index = [...]uint8{0, 11, 21, 32}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
