// Code generated by "stringer -type=AggregatorType -output generated.aggregatortype_string.go"; DO NOT EDIT.

package fold

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownAggregator-0]
	_ = x[RightAggregator-1]
	_ = x[LeftAggregator-2]
	_ = x[PerfectAggregator-3]
}

const _AggregatorType_name = "UnknownAggregatorRightAggregatorLeftAggregatorPerfectAggregator"

var _AggregatorType_index = [...]uint8{0, 17, 32, 46, 63}

func (i AggregatorType) String() string {
	if i < 0 || i >= AggregatorType(len(_AggregatorType_index)-1) {
		return "AggregatorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AggregatorType_name[_AggregatorType_index[i]:_AggregatorType_index[i+1]]
}
